prefix ids: <https://schema.industrialdataspace.org/>
prefix dcat: <http://www.w3.org/ns/dcat#>

template st:start {

    kg:write("/tmp/diagram_all_classes.plantuml", st:call-template(ids:all_classes))

}
where  {
}
