prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix dcat: <http://www.w3.org/ns/dcat#>

template st:start {

    kg:write("/tmp/classes.dot", st:call-template(ids:uml))

}
where  {
}
