prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix dcat: <http://www.w3.org/ns/dcat#>

template st:start {

    if (bound(?instance),
        st:call-template(ids:class-abox, ?class),
        st:call-template(ids:class-tbox, ?class))

    kg:write(concat("/tmp/",strafter(str(?class), "#"), ".dot"),
        st:call-template(ids:process-class-to-uml, ?class))

}
where  {
    ?class a owl:Class.
    OPTIONAL {
        ?instance a ?class
    }
}
group by ?class
