prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:process-relations-to-uml {

    "\n"
    "\t" str(?classA) " -> " str(?classB) " [\n\t\tarrowhead=vee\n"

    "\t\theadlabel = \"" st:call-template(ids:uml-headlabel, ?domain, ?property) "\""
    "\t\txlabel= \"" str(?propLabel) "\""

    "\n\t]"

}
where {
    ?property rdfs:domain ?domain;
        rdfs:range ?range;
        rdfs:label ?propLabel.

    ?domain rdfs:label ?classA.
    ?range rdfs:label ?classB.

    FILTER (strstarts(str(?domain), str(<ids:>)) && strstarts(str(?range), str(<ids:>)))

}

