prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:process-class-to-enum(?class) {

    "package de.fraunhofer.iais.eis;\n\n"
    "/* " str(?comment) " */\n"
    "\n@de.fhg.iais.jrdfb.annotation.RdfType(\"" str(?class) "\")"
    "\n"
    "public enum " strafter(str(?class), "#") " {\n"

        st:call-template(ids:process-enum-individuals, ?class)

    "\n}\n"

}
where{
    ?class a owl:Class;
        rdfs:comment ?comment.
}
