prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:process-class-to-uml {

    "\n"
    "\t" str(?label) " [\n"
    "\t\tlabel = \"{" str(?label) " | attributes | methods}\"\n"
    "\t]\n"

}
where {
    ?class a owl:Class;
        rdfs:label ?label.
}

