prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:process-class-to-bean(?class) {

    "package de.fraunhofer.iais.eis;\n"
    "\nimport de.fraunhofer.iais.eis.util.VocabUtil;"
    "\n"
    "\n"
    "/* " str(?comment) " */\n"
    "public class " concat(strafter(str(?class), "#"), "Impl")
    " implements " strafter(str(?class), "#")

    " {\n"

    # boilerplate methods

    "\n\t@javax.validation.constraints.NotNull java.net.URL url;"
    "\n"

    "\n\t// instance fields as derived from vocabulary\n"
    st:call-template(ids:subclass-properties-to-fields, ?class)

    "\n"
    "\n\t// no manual construction"
    "\n\t" strafter(str(?class), "#") "Impl() {}"
    "\n"
    "\n\t@Override"
    "\n\tfinal public java.net.URL getId() {"
    "\n\t\treturn url;"
    "\n\t}"
    "\n"
    "\n\tpublic String toRdf() {"
    "\n\t\treturn de.fraunhofer.iais.eis.util.VocabUtil.toRdf(this);"
    "\n\t}"
    "\n"

    # method implementation

    "\n\t// accessor method implementations as derived from vocabulary"
    "\n"
    st:call-template(ids:subclass-properties-to-methods, ?class, 'bean')

    "\n}\n"

}
where{
    ?class a owl:Class;
        rdfs:comment ?comment.
}
