prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:process-class-to-uml(?class) {

    "digraph G {\n"

    "\tfontname = \"Bitstream Vera Sans\"\n"
    "\tfontsize = 8\n"

    "\tnode [\n"
    "\tfontname = \"Bitstream Vera Sans\"\n"
    "\tfontsize = 8\n"
    "\tshape = \"record\"\n"
    "\t]\n"

    "\t" str(?label) " [\n"
    "\t\tlabel = \"{" str(?label) " | attributes | methods}\"\n"
    "\t]\n"

    "}\n"

}
where {
    ?class rdfs:label ?label.

}

