prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>

template ids:propertyAnnotation(?constraint, ?range) {

    if (str(?constraint) = "@OneToMany", "java.util.Collection<", concat(str(?constraint), " "))

    # return type
    st:call-template(ids:range, ?range)

    if (str(?constraint) = "@OneToMany", ">", "")
}
where {
}
