prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix valid: <http://industrialdataspace.org/2017/01/ids/validation#>

template ids:property-to-field(?property, ?class) {

    "\n\t"

    st:call-template(ids:propertyAnnotation, ?class, ?property, ?range)

    " "

    st:call-template(ids:range-to-java-type, ?class, ?property, ?range)

    " "
    strafter(str(?property), "#")
    ";"

}
where  {
   ?property rdfs:range ?range.
} 
