prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix valid: <http://industrialdataspace.org/2017/01/ids/validation#>

template ids:property-to-field(?property, ?class) {

    "\n\t"
    if (bound(?constraint),
        st:call-template(ids:propertyAnnotation, ?constraint, ?range),
        st:call-template(ids:range, ?range))

    " "
    strafter(str(?property), "#")
    ";"

}
where  {
   ?property rdfs:range ?range.

    OPTIONAL {
        ?property rdfs:domain ?class.
        ?class ids:validation ?validation.
        ?validation owl:onProperty ?property.
        ?validation valid:constraint ?constraint.
    }
} 
