prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:subclass-to-interface-extends(?class) {

    ", " strafter(str(?superClass), "#")

}
where {
    ?class rdfs:subClassOf ?superClass.
    FILTER (strstarts(str(?superClass), str(<ids:>)))
}
