prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template idstt:anything-to-comment(?thing) {
	"\n\t" ?com
}
WHERE {
    { ?thing rdfs:label ?com . }
	UNION
	{ ?thing rdfs:comment ?com . }
}
