prefix ids: <https://w3id.org/idsa/core/>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template ids:class-abox(?class) {

    kg:write(concat("/tmp/", st:call-template(idstt:to_class_name, ?class), ".java"),
        st:call-template(ids:process-class-to-enum, ?class))

}
where  {}


