prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix idsm: <https://w3id.org/idsa/metamodel/>

template idstt:class-tbox(?class) {

    if (!bound(?isAbstract) || (?isAbstract = false),
        kg:write(
            concat("/tmp/", st:call-template(idstt:to_class_name, ?class), "Impl.java"),
            st:call-template(idstt:process-class-to-bean, ?class)
        ),
    '')

    if (!bound(?isAbstract) || (?isAbstract = false),
        kg:write(
            concat("/tmp/", st:call-template(idstt:to_class_name, ?class), "Builder.java"),
            st:call-template(idstt:process-class-to-builder, ?class)
        ),
    '')

    kg:write(
        concat("/tmp/", st:call-template(idstt:to_class_name, ?class), ".java"),
        st:call-template(idstt:process-class-to-interface, ?class)
    )

}
where  {
    ?class a owl:Class.
    optional {?class idsm:abstract ?isAbstract}
}

