prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix idsm: <https://w3id.org/idsa/metamodel/>

template idstt:class-to-json-annotation(?class) {

    if (bound(?abstract),
        "",
        concat(
            "\n@JsonSubTypes.Type(value = ",
            st:call-template(idstt:to_class_name, ?class),
            "Impl.class),"
        )
    )

    st:call-template(idstt:subclass-to-json-annotation, ?class)
}
WHERE {
    ?class a owl:Class.

    optional {
        ?class idsm:abstract ?abstract.
    }

}


