prefix ids: <https://w3id.org/ids/core/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix idsm: <https://w3id.org/ids/metamodel/>
prefix idstt: <https://w3id.org/ids/transformationtemplates/>

template ids:getter-method-body(?property) {

    " {"

    "\n\t\treturn _"

        st:call-template(idstt:to_property_name, ?property)

     ";"

    "\n\t}"

}
where{
    ?property rdfs:range ?range.
}
