prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:jackson-annotation(?range, ?isCollection) {

    "@JsonDeserialize("

    if (?isCollection, "contentAs", "as")

    " = "

    st:call-template(idstt:to_class_name, ?range)

    "Impl.class)\n\t"
}
where {}
