prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix idsm: <https://w3id.org/idsa/metamodel/>

template idstt:jackson-plural-setter-annotation(?property) {
    if (bound(?pluralLabel),
        concat("@JsonAlias({\"", str(?pluralLabel), "\", \"", st:call-template(idstt:to_class_name, ?property) , "\"})"),
        "")
}
where {
    ?property a ?type.

    OPTIONAL {?property idsm:labelPluralForm ?pluralLabel}
    FILTER (?type IN (owl:ObjectProperty, owl:DatatypeProperty))
}