prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix dct: <http://purl.org/dc/terms/>
prefix idsm: <https://w3id.org/idsa/metamodel/>

template idstt:process-enum-individuals(?class) {

    if (bound(?comment),
        concat("\n\t/** ", str(?comment), " */"),
        if (bound(?label),
            concat("\n\t/** ", str(?label), " */"),
            '')
        )

    "\n\t"
    ucase(st:call-template(idstt:to_class_name, ?individual))

    "(\"" str(?individual) "\"),"
}
where  {
    ?individual a ?class.

    OPTIONAL {
        ?individual rdfs:label ?label.
    }

    OPTIONAL {
        ?individual rdfs:comment ?comment.
    }

}
