prefix ids: <https://w3id.org/idsa/core/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template ids:process-class-to-interface(?class) {

    "package de.fraunhofer.iais.eis;"
    "\n"

    st:call-template(ids:basic-imports)

    "\n\n"

    "/** " str(?comment) " */"
    "\n@RdfType(\"" str(?class) "\")"
    "\n@JsonTypeInfo(use=JsonTypeInfo.Id.MINIMAL_CLASS, property=\"@class\")"
    "\n"
    "public interface " st:call-template(idstt:to_class_name, ?class)

    if (bound(?superClass) && strstarts(str(?superClass), str(<ids:>)),
        concat(" extends ", strafter(st:call-template(ids:subclasses-to-list, ?class), ", ")),
        "")

    " {\n"

        "\n\t// standard methods\n"

        "\n\t@RdfId"
        "\n\t@javax.validation.constraints.NotNull URL getId();"
        "\n\tString toRdf();"
        "\n"
        "\n\t// accessor methods as derived from information model"
        "\n"

        st:call-template(ids:properties-to-interface-methods, ?class)

    "\n}\n"

}
where{
    ?class a owl:Class;
        rdfs:comment ?comment.

    optional {
        ?class rdfs:subClassOf ?superClass.
    }
}
GROUP BY ?class
