prefix ids: <https://w3id.org/ids/core/>
prefix dct: <http://purl.org/dc/terms/>

template ids:process-enum-individuals(?class) {

    if (bound(?comment),
        concat("\n\t/** ", str(?comment), " */"),
        '')

    "\n\t@RdfUri(\"" str(?individual) "\")"

    "\n\t" str(?identifier)

    if (bound(?label),
        concat("(\"", str(?label), "\"),"),
        concat("(\"", str(?identifier), "\"),"))

}
where  {
    ?individual a ?class;
        dct:identifier ?identifier.

    OPTIONAL {
        ?individual rdfs:comment ?comment.
    }

    OPTIONAL {
        ?individual rdfs:label ?label.
    }

}
