prefix ids: <https://w3id.org/ids/core/>
prefix idsm: <https://w3id.org/ids/metamodel/>
prefix idstt: <https://w3id.org/ids/transformationtemplates/>

template ids:property-to-field(?property, ?class) {

    "\n\t"

    if (!bound(?isAbstract) && !bound(?instance) && strstarts(str(?range), str(<ids:>)),
        st:call-template(idstt:jackson-annotation, ?range, bound(?relationType) && (?relationType = <idsm:OneToMany>)),
        "")

    st:call-template(ids:propertyAnnotation, ?class, ?property, ?range)

    " "

    st:call-template(ids:range-to-java-type, ?class, ?property, ?range, "<? extends ", ">")

    " "
    st:call-template(idstt:to_property_name, ?property)
    ";"
}
where  {
   ?property rdfs:range ?range;
        rdfs:domain ?class

   OPTIONAL {?instance a ?range}
   OPTIONAL {?range idsm:isAbstract ?isAbstract}

   OPTIONAL {
       ?class idsm:validation ?validation.
       ?validation idsm:forProperty ?property.
       ?validation idsm:relationType ?relationType.
   }
}
GROUP BY ?range
