prefix ids: <https://w3id.org/idsa/core/>

template ids:properties-to-interface-methods(?class) {

	# Iterates on selected properties and writes getter and setter methods

    # getter method signature

    # javadoc
    if (bound(?comment),
        concat("\n\t/** ", str(?comment), " */"),
        "")

    "\n\t@RdfProperty(\"" str(?property) "\")"

	st:call-template(ids:property-to-getter-method, ?property, ?class) ";"

}
where  {   
  ?property rdfs:domain ?class.

  OPTIONAL {
    ?property rdfs:comment ?comment.
  }
}
