prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix idsm: <https://w3id.org/idsa/metamodel/>

template idstt:properties-to-enum-methods(?class) {

	# Iterates on selected properties and writes getter and setter methods

    "\n"
    "\n\t@JsonIgnore"
	"\n\t"

    # visibility modifier
    "final public "

    # signature
	st:call-template(idstt:property-to-getter-method, ?property, ?class)

	" {\n\t"
	"\t//not implemented for enums\n\t"
	"\tthrow new UnsupportedOperationException();\n\t"
	"}\n\t"

}
where  {   
    ?property rdfs:domain ?class.
}
