prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:properties-to-builder-methods(?class, ?superClass) {

	# Iterates on selected properties and writes getter and setter methods

    "\n"
	"\n\t"

    # visibility modifier
    "final public "

    # return type and name
    st:call-template(idstt:to_class_name, ?class) "Builder "

	st:call-template(idstt:property-to-setter-method, ?property, ?class, true)

    # method body
	st:call-template(idstt:setter-method-builder-body, ?property, ?class)

}
where  {
      {?property rdfs:domain ?superClass.}
      UNION
      {?property rdfs:domain/owl:unionOf/rdf:rest*/rdf:first ?superClass.}
}
