prefix ids: <https://w3id.org/idsa/core/>
prefix idsm: <https://w3id.org/idsa/metamodel/>

template ids:propertyAnnotation(?class, ?property) {

    if (?constraint = <idsm:NotNull>, "@NotNull",
    if (?constraint = <idsm:NotEmpty>, "@NotEmpty",
      "!!unknownConstraint!!"))

}
where {
    ?class idsm:validation ?validation.
    ?validation idsm:forProperty ?property.
    ?validation idsm:constraint ?constraint.
}
