prefix ids: <https://w3id.org/ids/core/>
prefix valid: <https://schema.iais.fraunhofer.de/ids/helper/relation/>
prefix idsm: <https://w3id.org/ids/metamodel/>
prefix idstt: <https://w3id.org/ids/transformationtemplates/>

template ids:property-to-field(?property, ?class) {

    "\n\t"

    st:call-template(ids:propertyAnnotation, ?class, ?property, ?range)

    " "

    st:call-template(ids:range-to-java-type, ?class, ?property, ?range, "<? extends ", ">")

    " "
    st:call-template(idstt:to_property_name, ?property)
    ";"
}
where  {
   ?property rdfs:range ?range.
}
