prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix idsm: <https://w3id.org/idsa/metamodel/>

template idstt:property-to-field(?property, ?class) {

    "\n\t"
    st:call-template(idstt:jackson-plural-setter-annotation, ?property)
    "\n\t"
    st:call-template(idstt:jackson-plural-getter-annotation, ?property)
    "\n\t"

    st:call-template(idstt:propertyAnnotation, ?class, ?property)

    "@JsonAlias({\"ids:" st:call-template(idstt:to_property_name, ?property) "\", \"" st:call-template(idstt:to_property_name, ?property) "\"})"
    "\n\t"

    " "

    st:call-template(idstt:range-to-java-type, ?class, ?property, ?range, "<? extends ", ">")

    " _"
    st:call-template(idstt:to_property_name, ?property)
    ";"
}
where  {
   ?property rdfs:range ?range.
}
