prefix ids: <https://w3id.org/idsa/core/>
prefix idsm: <https://w3id.org/idsa/metamodel/>
prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template ids:property-to-getter-method(?property, ?class) {

    "\n\t"
    st:call-template(ids:range-jackson-annotation, ?property, ?range)
    "\n\t"
    st:call-template(ids:range-to-java-type, ?class, ?property, ?range, "<? extends ", ">")

    " "

    # method name
    "get"

    concat(
        ucase(substr(str(st:call-template(idstt:to_property_name, ?property)), 1, 1)),
        substr(str(st:call-template(idstt:to_property_name, ?property)), 2),
        '()')

}
where  {
    ?property rdfs:range ?range;
        rdfs:label ?label.

    OPTIONAL {?property idsm:labelPluralForm ?pluralLabel}
}
