prefix ids: <https://w3id.org/idsa/core/>
prefix idsm: <https://w3id.org/idsa/metamodel/>

template ids:properties-to-fields(?class) {

	# Iterates on selected properties
	st:call-template(ids:property-to-field, ?property, ?class)

}
where  {
    ?class ^rdfs:domain|(idsm:validation/idsm:forProperty) ?property .
}
group by ?property
