prefix ids: <https://w3id.org/ids/core/>
prefix idsm: <https://w3id.org/ids/metamodel/>
prefix idstt: <https://w3id.org/ids/transformationtemplates/>

template ids:property-to-setter-method(?property, ?class) {

    # method name

    "_"
    st:call-template(idstt:to_property_name, ?property)
    "_"

    # method params
    "("
        # parameter type and annotation
        st:call-template(ids:propertyAnnotation, ?class, ?property, ?range)

        " "
        st:call-template(ids:range-to-java-type, ?class, ?property, ?range, "<? extends ", ">")
        " _"

        # parameter label
        st:call-template(idstt:to_property_name, ?property)
        "_"
    ")"

}
where  {
    ?property rdfs:range ?range.
}
