prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix idsm: <https://w3id.org/idsa/metamodel/>

template idstt:subclass-properties-to-fields(?class) {

    # Iterates on selected properties
    st:call-template(idstt:property-to-field, ?property, ?superClass)

}
where {
    ?class a owl:Class;
        rdfs:subClassOf* ?superClass.

    ?superClass ^rdfs:domain|(idsm:validation/idsm:forProperty) ?property .
}
group by ?property