prefix ids: <https://w3id.org/idsa/core/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:subclass-properties-to-fields(?class) {

    st:call-template(ids:properties-to-fields, ?superClass, 'bean')

}
where {
    ?class a owl:Class;
        rdfs:subClassOf* ?superClass.

}
