prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix idoc: <http://industrialdataspace.org/2017/01/ids/documentation#>

template ids:getter-method-body(?property) {

    " {"

    "\n\t\treturn "

    if (strends(str(?range), "PlainLiteral"),
        concat("PlainLiteral.toPlainLiteralCollection(", if (bound(?pluralLabel), str(?pluralLabel), str(?label)), ")"),
        if (bound(?pluralLabel), str(?pluralLabel), str(?label)))

     ";"

    "\n\t}"

}
where{
    ?property rdfs:range ?range;
        rdfs:label ?label.

    OPTIONAL {?property idoc:labelPluralForm ?pluralLabel}
}
