prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix idoc: <http://industrialdataspace.org/2017/01/ids/documentation#>

template ids:property-to-setter-method(?property, ?class) {

    # method params
    "("
        # parameter type and annotation
        st:call-template(ids:propertyAnnotation, ?class, ?property, ?range)

        " "

        st:call-template(ids:range-to-java-type, ?class, ?property, ?range, "<? extends ", ">")

        " "

        # parameter label
        if (bound(?pluralLabel), str(?pluralLabel), str(?label))
    ")"

}
where  {
    ?property rdfs:range ?range;
        rdfs:label ?label.

    OPTIONAL {?property idoc:labelPluralForm ?pluralLabel}
}
