prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix valid: <http://industrialdataspace.org/2017/01/ids/validation#>

template ids:propertyAnnotation(?class, ?property, ?range) {

    str(?constraint)

}
where {
    ?class ids:validation ?validation.
    ?validation owl:onProperty ?property.
    ?validation valid:constraint ?constraint.
}
