prefix ids: <https://w3id.org/ids/core/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dct: <http://purl.org/dc/terms/>
prefix idsm: <https://w3id.org/ids/metamodel/>

template ids:enum-values-to-uml(?class) {

    "# " str(?identifier)

}
where {
    ?instance a ?class;
        idsm:constantIdentifier ?identifier.
}
limit 15


