prefix ids: <https://w3id.org/idsa/core/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:properties-to-uml(?class) {

    "# " str(?label) " : "

    st:call-template(ids:range-to-java-type, ?class, ?property, ?range, "<", ">")

}
where {
    ?property rdfs:domain ?class;
        rdfs:range ?range;
        rdfs:label ?label.

    filter (!(strstarts(str(?range), str(<ids:>))))
}
