#
# Copyright (c) 2021 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e. V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:create-builder-interface-with-map {

    st:call-template(idstt:get-license)
    st:call-template(idstt:get-package, 'builder')

    "\nimport java.util.Map;\n"

    if(?hasId,
        "import de.fraunhofer.iais.eis.util.*;\n",
        ""
    )

    "\npublic interface Builder<T> {\n"

    "\n\tT build()"
    if(?hasId,
        " throws ConstraintViolationException;",
        ";"
    )
    "\n\tMap<String, Object> getValueMap();"

    "\n\n}"
}
WHERE {
    BIND( st:has-id-label-comment() as ?hasId )
}
