prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:create-model-class {

    st:call-template(idstt:get-package, 'interface')

    "\npublic interface ModelClass {\n"

    "\n\tpublic Object deepCopy();"

    "\n\n}"

}
WHERE {}