prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:create-builder-interface {

    st:call-template(idstt:get-license)
    st:call-template(idstt:get-package, 'builder')

    "\npublic interface Builder<T> {\n"

    "\n\tpublic T build();"

    "\n\n}"
}
WHERE {}