prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:create-builder-interface {

    st:call-template(idstt:get-package, 'interface')

    "\nimport java.util.Map;\n"

    if(?hasId,
        "import de.fraunhofer.iais.eis.util.*;\n",
        ""
    )

    "\npublic interface Builder<T> {\n"

    "\n\tT build()"
    if(?hasId,
        " throws ConstraintViolationException;",
        ";"
    )
    "\n\tMap<String, Object> getValueMap();"

    "\n\n}"
}
WHERE {
    BIND( st:has-id-label-comment() as ?hasId )
}