prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:get-class-field-names-formatted(?class) {

    if(bound(?property),
            ", ",
            ""
        )
        group {
            format {
                "this.%s"
                ?field 
            }
            ; separator = ", "}
    
}
WHERE  {
    OPTIONAL {
        {
            ?property rdfs:domain ?class .
            BIND(st:call-template(idstt:to_java_field_name, ?property) as ?field )
        }
        UNION
        {   
            ?property rdfs:domain/owl:unionOf/rdf:rest*/rdf:first ?class .
            BIND(st:call-template(idstt:to_java_field_name, ?property) as ?field )
        }
    }
}