prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:get-javadoc(?class, ?property) {

    "\n\t/**"
    st:call-template(idstt:get-javadoc-description, ?property)
    st:call-template(idstt:get-javadoc-return, ?class, ?property)
    "\n\t*/"

}
where  {}
