prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:get-javadoc(?class, ?property, ?isSetterFunction) {

    "\n\t/**"
    st:call-template(idstt:get-javadoc-description, ?property)
    "\n\t*\n\t* More information under " str(?property)
    "\n\t*"
    if(?isSetterFunction, st:call-template(idstt:get-javadoc-setter-param, ?property, ?class) , st:call-template(idstt:get-javadoc-return, ?class, ?property))
    "\n\t*/"

}
where  {}
