prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:get-class-equals-body-properties(?class) {

    group {
        format {
            CONCAT(if(regex(?fieldType, "\\[\\]"), "Arrays.equals", "Objects.equals"), "(this.%s, other.%s)")
            ?field ?field
        }
        ; separator = " &&\n\t\t\t\t"}
    
}
WHERE  {
    ?class rdfs:subClassOf* ?superClass .
    OPTIONAL {
        {
            ?property rdfs:domain ?superClass ;
            rdfs:range ?range .
            BIND(st:call-template(idstt:to_java_field_name, ?property, ?superClass) as ?field )
            BIND(st:call-template(idstt:range-to-java-type, ?class, ?property, ?range, '<', '>') as ?fieldType )
        }
        UNION
        {   
            ?property rdfs:domain/owl:unionOf/rdf:rest*/rdf:first ?superClass .
            BIND(st:call-template(idstt:to_java_field_name, ?property, ?superClass) as ?field )
            BIND(st:call-template(idstt:range-to-java-type, ?class, ?property, ?range, '<', '>') as ?fieldType )
        }
    }
}