prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:get-class-field-names-formatted(?class) {

    group {
        format {
            "this.%s"
            ?field 
        }
        ; separator = ",\n\t\t\t"}
    
}
WHERE  {
    ?class rdfs:subClassOf* ?superClass .
    OPTIONAL {
        {
            ?property rdfs:domain ?superClass .
            BIND(st:call-template(idstt:to_java_field_name, ?property, ?superClass) as ?field )
        }
        UNION
        {   
            ?property rdfs:domain/owl:unionOf/rdf:rest*/rdf:first ?superClass .
            BIND(st:call-template(idstt:to_java_field_name, ?property, ?superClass) as ?field )
        }
    }
}