#
# Copyright (c) 2021 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e. V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template idstt:get-all-comments(?thing) {
	group {
		"new TypedLiteral("
		#if comment is a string with language tag, then split it up into: start quote, string value, end quote, separate via comma and then start quote, language, end quote
		#Otherwise just dump the comment, which already contains quotes
		#Furthermore, a label/comment in RDF may contain multiple lines. We cannot paste it "as is" into java. So we drop the line breaks.
		if (bound(?lang),
			#yes, language is present
			CONCAT(
				CONCAT(
					CONCAT(
						#Innermost first. Prepend a quotation mark
						CONCAT("\"",
						#Concatenate this with the stripped string (no line breaks)
							REPLACE(REPLACE(REPLACE(str(?comment), "\n", ""), "\r", ""), "\"", "\\\\\"")
						#Add quotation mark at the end
						), "\", \""
					#Append language
					), ?lang
				#Final quotation mark
				), "\""
			),

			#no language present. Strip string of all line breaks and escape quotation marks
			REPLACE(REPLACE(REPLACE(?comment, "\n", ""), "\r", ""), "\"", "\\\\\""))
		")" ; separator = ", "
	}
}
WHERE {
    ?thing rdfs:comment ?comment .
	#Test if the string is localized
	OPTIONAL { BIND( LANG(?comment) AS ?lang ) . }
}
