prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

template idstt:get-javadoc-description(?thing) {
	group { "\n\t* " STR(?com) ; separator = "" }
}
WHERE {
	{ ?thing rdfs:comment ?com . }
	UNION
	{ ?thing skos:note ?com . }
	UNION
	{ ?thing skos:scopeNote ?com . }
}
