prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:get-class-equals-body(?class) {

    " {"
    "\n\t\tif (this == obj) {"
    "\n\t\t\treturn true;"
    "\n\t\t} else if (obj == null) {"
    "\n\t\t\treturn false;"
    "\n\t\t} else if (this.getClass() != obj.getClass()) {"
    "\n\t\t\treturn false;"
    "\n\t\t}"
    
    # if no properties are present, only check the above
    if (bound(?hasProperties) && strlen(?hasProperties) > 1,
        # then
        concat(concat(concat(concat(concat(concat(concat(concat(
            " else {\n\t\t\t",
            st:call-template(idstt:to_bean_name, ?class)), " other = ("), st:call-template(idstt:to_bean_name, ?class)), ") obj;"),
            "\n\t\t\treturn "), st:call-template(idstt:get-class-equals-body-properties, ?class)), ";"),
            "\n\t\t}"),
        # else
        "\n\t\treturn true;"
    )   
    "\n\t}"
}
WHERE  {
    BIND(st:call-template(idstt:list-class-properties, ?class) AS ?hasProperties)
}