prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template idstt:process-class-to-enum(?class) {

    "package de.fraunhofer.iais.eis;\n"

    st:call-template(idstt:basic-imports)
    "\nimport com.fasterxml.jackson.databind.JsonNode;"

    "\nimport java.util.stream.Collectors;"
    "\nimport java.util.stream.Stream;"

    "\n\n"

    "/** " st:call-template(idstt:anything-to-comment, ?class) " \n*/"
    "\n@JsonFormat(shape = JsonFormat.Shape.OBJECT)"
    "\n@JsonTypeName(\"" st:call-template(idstt:to_full_identifier, ?class) "\")"    
    "\npublic enum " st:call-template(idstt:to_enum_name, ?class)

    " {\n"

    # Print all individuals and delete the last comma (must be replaced with a semi colon)
	if(STRLEN(st:call-template(idstt:process-enum-individuals, ?class)) > 2,
    SUBSTR(st:call-template(idstt:process-enum-individuals, ?class), 0, STRLEN(st:call-template(idstt:process-enum-individuals, ?class)) - 1),
	st:call-template(idstt:process-enum-individuals, ?class))

    ";"

    # add enum default properties
    st:call-template(idstt:enum-default-properties, ?class)

    "\n"
	"\n\t" st:call-template(idstt:to_enum_name, ?class) "(String id, List<TypedLiteral> label, List<TypedLiteral> comment) {"
	"\n\t\ttry {"
	"\n\t\t\tthis.id = new URI(id);"
	"\n\t\t\tthis.label = label;"
	"\n\t\t\tthis.comment = comment;"
    "\n\t\t}"
    "\n\t\tcatch (java.net.URISyntaxException e) {"
    "\n\t\t\tthrow new IllegalArgumentException(e);"
    "\n\t\t}"
	"\n\t}"

	# add enum default methods
    st:call-template(idstt:enum-default-methods, ?class)

    # superclass methods
    "\n"
    st:call-template(idstt:subclass-properties-to-methods, ?class, 'enum')

    "\n}\n"

}
WHERE {}
