prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:properties-to-interface-methods(?class) {

	# Iterates on selected properties and writes getter and setter methods

    # getter method signature

    # javadoc getter
    st:call-template(idstt:get-javadoc, ?class, ?property, false)

	st:call-template(idstt:property-to-getter-method, ?property, ?class, true) ";"
	
	"\n"
	# javadoc setter
	st:call-template(idstt:get-javadoc, ?class, ?property, true)
	
	"\n\tpublic void "
	st:call-template(idstt:property-to-setter-method, ?property, ?class, false) ";"
	

}
where  {
    {?property rdfs:domain ?class.}
    UNION
    {?property rdfs:domain/owl:unionOf/rdf:rest*/rdf:first ?class.}

}
