prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:properties-to-enum-methods(?class, ?superClass) {

	# Iterates on selected properties and writes getter and setter methods

    "\n"
    if(?useJackson, "\n\t@JsonIgnore", "")
	"\n\t"

    # signature
	st:call-template(idstt:property-to-getter-method, ?property, ?class, 'enum')

	" {\n\t"
	"\t//not implemented for enums\n\t"
	"\tthrow new UnsupportedOperationException();\n\t"
	"}\n\t"

}
where  {
      {?property rdfs:domain ?superClass.}
      UNION
      {?property rdfs:domain/owl:unionOf/rdf:rest*/rdf:first ?superClass.}
      BIND(st:add-jackson-annotations() AS ?useJackson)
}
