prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:properties-to-interface-methods(?class) {

	# Iterates on selected properties and writes getter and setter methods

    # getter method signature

    # javadoc
    st:call-template(idstt:get-javadoc, ?class, ?property)

	st:call-template(idstt:property-to-getter-method, ?property, ?class, true) ";"

}
where  {
    {?property rdfs:domain ?class.}
    UNION
    {?property rdfs:domain/owl:unionOf/rdf:rest*/rdf:first ?class.}

}
