prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:property-to-setter-method(?property, ?class, ?forBuilder) {

    # method name

    if (?forBuilder,
        # then
        st:call-template(idstt:property-to-builder-signature, ?property, ?class),
        # else
        concat("set",
        ucase(substr(str(st:call-template(idstt:property-to-getter-setter-signature, ?property, ?class)), 1, 1)),
        substr(str(st:call-template(idstt:property-to-getter-setter-signature, ?property, ?class)), 2),
        " "))

    # method params
    "("
        # parameter type
        st:call-template(idstt:range-to-java-type, ?class, ?property, ?range, "<", ">")
        " "

        # parameter label
        st:call-template(idstt:to_java_param_name, ?property, ?class)
    ")"

}
where  {
    ?property rdfs:range ?range.
}
