prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix dcat: <http://www.w3.org/ns/dcat#>

template idstt:start-static-files {

    kg:write(concat("/tmp/", "Builder.java"),
        st:call-template(idstt:create-builder-interface))

    kg:write(concat("/tmp/", "AbstractBuilder.java"),
        st:call-template(idstt:create-abstract-builder))

    # kg:write(concat("/tmp/", "ModelClass.java"),
    #     st:call-template(idstt:create-model-class))
    
}
where  {}

