prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix dcat: <http://www.w3.org/ns/dcat#>

template st:start {

    st:call-template(idstt:start-static-files)
    st:call-template(idstt:start-classes-and-instances)
    
}
where  {}
