prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template idstt:subclass-to-json-annotation(?class, ?target) {

    group {
        "\n\t"
		if(str(?target) = 'mixin', "@JsonSubTypes", #in Mixins, we always want Jackson
			if(?useJackson,
				"@JsonSubTypes",
				"@KnownSubtypes"
			)
		)
        ".Type(value = "

        st:call-template(idstt:to_interface_name, ?subClass)

        ".class)" ; separator = ","
    }
}
WHERE {
    ?class ^rdfs:subClassOf ?subClass.

    OPTIONAL {
        ?instance a ?subClass.
    }

    #No need to filter for namespace. We only look for subclasses of the current class, not for super classes.
    #External ontologies will not have subclass relations to our classes
    #BIND( st:get-namespace() as ?ns )
    #FILTER(STRSTARTS(STR(?subClass), STR(?ns)))
    BIND(st:add-jackson-annotations() AS ?useJackson)
}
