prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template idstt:subclasses-to-list(?class) {

    group { st:call-template(idstt:to_interface_name, ?superClass) ; separator = ", " }

}
where {
    ?class rdfs:subClassOf ?superClass.
    BIND( st:get-namespace() as ?ns )
    FILTER(STRSTARTS(STR(?superClass), STR(?ns)))
}
