prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template idstt:process-class-to-builder(?class) {

    "package de.fraunhofer.iais.eis;\n"

    st:call-template(idstt:basic-imports)

    "\n"
    "\n"
    "public class " st:call-template(idstt:to_class_name, ?class) "Builder"

    " {\n"

    "\n\tprivate " st:call-template(idstt:to_class_name, ?class) "Impl "

    lcase(substr(st:call-template(idstt:to_class_name, ?class), 1, 1))
    substr(st:call-template(idstt:to_class_name, ?class), 2)

    "Impl;"

    # constructor

    "\n"
    "\n\tpublic " st:call-template(idstt:to_class_name, ?class) "Builder() {"
    "\n\t\t"
        lcase(substr(st:call-template(idstt:to_class_name, ?class), 1, 1)) substr(st:call-template(idstt:to_class_name, ?class), 2) "Impl = new " st:call-template(idstt:to_class_name, ?class) "Impl();"
    "\n\t}"
    "\n"
    "\n\tpublic " st:call-template(idstt:to_class_name, ?class) "Builder(@javax.validation.constraints.NotNull URI id) {"
    "\n\t\t"
    "this();"
    "\n\t\t"
    lcase(substr(st:call-template(idstt:to_class_name, ?class), 1, 1)) substr(st:call-template(idstt:to_class_name, ?class), 2) "Impl.id = id;"
    "\n\t}"

    # method implementation

    st:call-template(idstt:subclass-properties-to-methods, ?class, 'builder')

    # build method

    "\n"
    "\n\tpublic final " st:call-template(idstt:to_class_name, ?class) " build() throws ConstraintViolationException {"
    "\n\t\tVocabUtil.getInstance().validate(" lcase(substr(st:call-template(idstt:to_class_name, ?class), 1, 1)) substr(st:call-template(idstt:to_class_name, ?class), 2) "Impl);"
    "\n\t\treturn " lcase(substr(st:call-template(idstt:to_class_name, ?class), 1, 1)) substr(st:call-template(idstt:to_class_name, ?class), 2) "Impl;"
    "\n\t}"

    "\n}\n"

}
where {}
