prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:properties-to-interface-methods(?class) {

	# Iterates on selected properties and writes getter and setter methods

    # getter method signature

    # javadoc
    "\t/**"
    st:call-template(idstt:anything-to-comment, ?property)
    "\n\t*/"

	st:call-template(idstt:property-to-getter-method, ?property, ?class) ";"

}
where  {
    {?property rdfs:domain ?class.}
    UNION
    {?property rdfs:domain/owl:unionOf/rdf:rest*/rdf:first ?class.}

}
