prefix ids: <https://schema.industrialdataspace.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dct: <http://purl.org/dc/terms/>
prefix ids_vis: <https://schema.iais.fraunhofer.de/ids/helper/visualization/>

template ids:package-content-subclass-relations(?package) {

    "\n"

    "\t" str(?firstClassLabel) " ..|> " str(?otherClass)


}
where {
    ?firstClass ids_vis:belongsToPackage ?package;
        a owl:Class;
        rdfs:label ?firstClassLabel.

    ?otherClass ids_vis:belongsToPackage ?package;
        a owl:Class;
        rdfs:label ?otherClassLabel.

    ?firstClass rdfs:subClassOf ?otherClass.
}



