prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix valid: <http://industrialdataspace.org/2017/01/ids/validation#>

template ids:uml-headlabel(?class, ?property) {

    if (bound(?relationType) && (?relationType = <valid:OneToMany>),

        # collection
        if (bound(?constraint) && (?constraint = <valid:NotEmpty>),
            " 1..* ",
            " * "),

        # single reference
        if (bound(?constraint) && ((?constraint = <valid:NotEmpty>) || (?constraint = <valid:NotNull>)),
            " 1 ",
            "")

        )

}
where {
    ?class valid:validation ?validation.
    ?validation valid:forProperty ?property.

    OPTIONAL {
        ?validation valid:relationType ?relationType.
    }

    OPTIONAL {
        ?validation valid:constraint ?constraint;
    }
}

