prefix ids: <https://schema.industrialdataspace.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:uml {

    "@startuml\n\n"
    "skinparam linetype ortho\n"
    "title Industrial Data Space Information Model - Class Diagram\n"

    st:call-template(ids:process-class-to-uml)
    st:call-template(ids:property-relations-to-uml)
    #st:call-template(ids:subclass-relations-to-uml)

    "@enduml\n"

}
where {
}

