prefix ids: <https://w3id.org/ids/core/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:process-class-to-bean(?class) {

    "package de.fraunhofer.iais.eis;\n"

    st:call-template(ids:basic-imports)

    "\n"
    "\n"
    "/** " str(?comment) " */\n"
    "public class " concat(str(?label), "Impl")
    " implements " str(?label)

    " {\n"

    # boilerplate methods

    "\n\t@javax.validation.constraints.NotNull URL id;"
    "\n"

    "\n\t// instance fields as derived from information model\n"
    st:call-template(ids:subclass-properties-to-fields, ?class)

    "\n"
    "\n\t// no manual construction"
    "\n\t" str(?label) "Impl() {}"
    "\n"
    "\n\t@Override"
    "\n\tfinal public URL getId() {"
    "\n\t\treturn id;"
    "\n\t}"
    "\n"
    "\n\tpublic String toRdf() {"
    "\n\t\treturn VocabUtil.getInstance().toRdf(this);"
    "\n\t}"
    "\n"

    # method implementation

    "\n\t// accessor method implementations as derived from information model"
    "\n"
    st:call-template(ids:subclass-properties-to-methods, ?class, 'bean')

    "\n}\n"

}
where{
    ?class a owl:Class;
        rdfs:comment ?comment;
        rdfs:label ?label .

    filter (lang(?label) = "en")
}
