prefix ids: <https://w3id.org/ids/core/>

template ids:properties-to-bean-methods(?class) {

	# Iterates on selected properties and writes getter and setter methods

    # getter method

	"\n\t"

    # visibility modifier
    "final public "

    # signature
	st:call-template(ids:property-to-getter-method, ?property, ?class)

    # method body
	st:call-template(ids:getter-method-body, ?property)

}
where  {   
  ?property rdfs:domain ?class;
    rdfs:label ?label.
}
