prefix ids: <https://w3id.org/ids/core/>
prefix idsm: <https://w3id.org/ids/metamodel/>

template ids:property-to-getter-method(?property, ?class) {

    "\n\t"

    st:call-template(ids:propertyAnnotation, ?class, ?property, ?range)

    "\n\t"

    st:call-template(ids:range-to-java-type, ?class, ?property, ?range, "<? extends ", ">")

    " "

    # method name
    "get"

    if (bound(?pluralLabel),
            concat(ucase(substr(str(?pluralLabel), 1, 1)), substr(str(?pluralLabel), 2), '()'),
            concat(ucase(substr(str(?label), 1, 1)), substr(str(?label), 2), '()'))

}
where  {
    ?property rdfs:range ?range;
        rdfs:label ?label.

    OPTIONAL {?property idsm:labelPluralForm ?pluralLabel}
}
