prefix ids: <https://schema.industrialdataspace.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:process-class-to-interface(?class) {

    "package de.fraunhofer.iais.eis;"
    "\n"

    st:call-template(ids:basic-imports)

    "\n\n"

    "/** " str(?comment) " */"
    "\n@RdfType(\"" str(?class) "\")"
    "\n"
    "public interface " str(?label)

    if (bound(?superClass) && strstarts(str(?superClass), str(<ids:>)),
        concat(" extends ", strafter(st:call-template(ids:subclass-to-interface-extends, ?class), ", ")),
        "")

    " {\n"

        "\n\t// standard methods\n"

        "\n\t@RdfId"
        "\n\t@javax.validation.constraints.NotNull java.net.URL getId();"
        "\n\tString toRdf();"
        "\n"
        "\n\t// accessor methods as derived from information model"
        "\n"

        st:call-template(ids:properties-to-interface-methods, ?class)

    "\n}\n"

}
where{
    ?class a owl:Class;
        rdfs:comment ?comment;
        rdfs:label ?label .

    filter (lang(?label) = "en")
    optional {
        ?class rdfs:subClassOf ?superClass.
    }
}
GROUP BY ?class
