prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix valid: <http://industrialdataspace.org/2017/01/ids/validation#>

template ids:propertyAnnotation(?class, ?property, ?range) {

    if (?constraint = <valid:NotNull>, "@NotNull",
    if (?constraint = <valid:NotEmpty>, "@NotEmpty",
      "!!unknownConstraint!!"))

}
where {
    ?class valid:validation ?validation.
    ?validation valid:forProperty ?property.
    ?validation valid:constraint ?constraint.
}
