prefix ids: <https://schema.industrialdataspace.org/>
prefix valid: <https://schema.iais.fraunhofer.de/ids/helper/relation/>

template ids:propertyAnnotation(?class, ?property, ?range) {

    if (?constraint = <valid:NotNull>, "@NotNull",
    if (?constraint = <valid:NotEmpty>, "@NotEmpty",
      "!!unknownConstraint!!"))

}
where {
    ?class valid:validation ?validation.
    ?validation valid:forProperty ?property.
    ?validation valid:constraint ?constraint.
}
