prefix ids: <https://schema.industrialdataspace.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:subclass-to-interface-extends(?class) {

    ", " str(?superClassLabel)

}
where {
    ?class rdfs:subClassOf ?superClass;
        rdfs:label ?superClassLabel .

    filter (strstarts(str(?superClass), str(<ids:>)) && lang(?superClassLabel) = "en")
}
