#
# Copyright (c) 2021 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e. V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:create-schema-validator {

    st:call-template(idstt:get-package, 'serialization')
    st:call-template(idstt:basic-imports)

    "\n\t/**"
    "\n\t* Validator that can validate a serialized AASEnvironment according to a"
    "\n\t* specific schema."
    "\n\t*/"
    "\npublic interface SchemaValidator {\n"
    "\n\n\t"
         "\n\t\t/**"
         "\n\t\t* Validate a serialized AASEnvironment according to a specific Schema. Does not"
         "\n\t\t* contain any additional validation, but is restricted to schema validation"
         "\n\t\t* only."
         "\n\t\t* "
         "\n\t\t* @param serializedAASEnvironment A string-serialized AASEnvironment."
         "\n\t\t* @return Set of validation errors. If validation succeeds, the Set is empty."
         "\n\t\t*/"
        "public Set<String> validateSchema(String serializedAASEnvironment);"
    "\n\n}"
}
WHERE {
}
