prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:custom-static-files {
    kg:write(concat("/tmp/", st:call-template(idstt:package-to-path, 'interface'), "LangString.java"),
                    st:call-template(idstt:create-lang-string))
    kg:write(concat("/tmp/", st:call-template(idstt:package-to-path, 'annotations'), "IRI.java"),
                    st:call-template(idstt:create-iri))
    kg:write(concat("/tmp/", st:call-template(idstt:package-to-path, 'annotations'), "KnownSubtypes.java"),
                    st:call-template(idstt:create-known-subtypes))

    kg:write(concat("/tmp/", st:call-template(idstt:package-to-path, 'builder'), "Builder.java"),
        st:call-template(idstt:create-builder-interface))
    kg:write(concat("/tmp/", st:call-template(idstt:package-to-path, 'builder'), "AbstractBuilder.java"),
            st:call-template(idstt:create-abstract-builder))
    kg:write(concat("/tmp/", st:call-template(idstt:package-to-path, 'builder'), "ExtendableBuilder.java"),
            st:call-template(idstt:create-extendable-builder))
}
where  {}

