prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:to_bean_name(?class) {
    concat(
        "Default",
        replace(str(?class), "^.*[/#]([^/#]+)/?", "$1")
    )
}
where {}
