prefix idstt: <https://w3id.org/idsa/transformationtemplates/>


template idstt:to_java_param_name(?property, ?class) {
    if (?allowsList,
        # then
        REPLACE(IRI(st:call-template(idstt:to_plural_form, ?propertyFieldName)), "\"", ""),
        # else
        REPLACE(IRI(?propertyFieldName), "\"", "")
    )
    
}
WHERE {
    BIND( st:call-template(idstt:property-allows-list, ?property, ?class) AS ?allowsList)
    BIND( st:call-template(idstt:to_java_property_name, ?property) AS ?propertyFieldName)
}