prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

# Helper template, only returns anything, if there is a subclass relation.
# Not to be used directly from outside of "check-subclass-relation.rq"

template idstt:get-subclass-relation(?superClass, ?class) {

    true

}
WHERE {
    ?class rdfs:subClassOf* ?otherClass .
    FILTER(?otherClass = ?superClass)
}
