prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix sh: <http://www.w3.org/ns/shacl#>

template idstt:property-allows-list(?property, ?class) {
   
    if ( ?isArray,
        # then
        true,
        # else
        false
    )

}
WHERE {
    {?property rdfs:domain/^(rdfs:subClassOf*) ?class.} UNION {
    ?property rdfs:domain/owl:unionOf/rdf:rest*/rdf:first/^(rdfs:subClassOf*) ?class.}

    OPTIONAL {
        ?class rdfs:subClassOf* ?superClass .
        ?classShape sh:targetClass ?superClass ;
            (sh:xone|sh:or)*/rdf:rest*/rdf:first*/sh:property ?propertyShape .
        ?propertyShape sh:path ?property ;
        sh:maxCount ?maxCount .
    }

    BIND(
        if ( BOUND(?maxCount), 
            # -> [?, max]
            if ( ?maxCount > 1,
                # then -> multiple values allowed
                true,
                # else -> at most 1 value allowed
                false
            ),
            # no max cardinality bound [?, *]
            true
        ) AS ?isArray
    )

} LIMIT 1
