prefix ids: <https://w3id.org/idsa/core/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix idsm: <https://w3id.org/idsa/metamodel/>

template ids:range-to-java-type(?class, ?property, ?range, ?bracketOpen, ?bracketClose) {

    if (bound(?relationType) && (?relationType = <idsm:OneToMany>), concat("java.util.ArrayList", str(?bracketOpen)), "")

    st:call-template(ids:range-to-basic-type, ?property, ?range)

    if (bound(?relationType) && (?relationType = <idsm:OneToMany>), str(?bracketClose), "")

}
where {
    ?property rdfs:range ?range.

    OPTIONAL {
        ?class idsm:validation ?validation.
        ?validation idsm:forProperty ?someProperty.
        ?property rdfs:subPropertyOf? ?someProperty.
        ?validation idsm:relationType ?relationType.
    }
}
