prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix idsm: <https://w3id.org/idsa/metamodel/>

template idstt:to_class_name(?classresource) {
    replace(str(?classresource), "^.*/([^/]+)/?", "$1")
}
where {}
