prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:to_java_property_name(?property) {
    LCASE( SUBSTR( STR(?shortDomain), 1, 1)) SUBSTR( STR(?shortDomain), 2)
    UCASE( SUBSTR( STR(?shortId), 1, 1)) SUBSTR( STR(?shortId), 2)
}
where {
    ?property rdfs:domain ?domain .
    BIND( st:call-template(idstt:to_short_identifier, ?property) as ?shortId )
    BIND( st:call-template(idstt:to_short_identifier, ?domain) as ?shortDomain )
}
