prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:custom-static-files {

    if(?hasModelSuperclass,
        kg:write(concat("/tmp/", st:call-template(idstt:package-to-path, 'builder'), "ModelClass.java"),
            st:call-template(idstt:create-model-class)),
        ""
    )

    if(?hasMap,
        kg:write(concat("/tmp/", st:call-template(idstt:package-to-path, 'builder'), "Builder.java"),
            st:call-template(idstt:create-builder-interface-with-map)),
        ""
    )

    if(?hasMap,
        kg:write(concat("/tmp/", st:call-template(idstt:package-to-path, 'builder'), "AbstractBuilder.java"),
            st:call-template(idstt:create-abstract-builder-with-map)),
        ""
    )

    if(?hasMap,
        kg:write(concat("/tmp/", st:call-template(idstt:package-to-path, 'builder'), "Util.java"),
            st:call-template(idstt:create-util)),
        ""
    )
}
where  {
    BIND( st:has-builder-with-map() as ?hasMap )
    BIND( st:has-superclass-of-all-classes() as ?hasModelSuperclass )
}

