prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:interface-default-methods {

    "\n\t@JsonProperty(\"@id\")"
    "\n\t@NotNull"
    "\n\tpublic URI getId();"
    
    "\n\tpublic List<TypedLiteral> getLabel();"
    
    "\n\tpublic List<TypedLiteral> getComment();"
    
    "\n\tpublic String toRdf();"
    "\n"
    
    "\n\t// getter and setter for generic property map"
    "\n\tpublic Map<String,Object> getProperties();"
    "\n\tpublic void setProperty(String property, Object value);"
    "\n"

}
where {}