prefix idstt: <https://w3id.org/idsa/transformationtemplates/>


template idstt:property-to-builder-signature(?property) {
    CONCAT(CONCAT("_", st:call-template(idstt:to_java_property_name, ?property)), "_")
}
where {}