prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix sh: <http://www.w3.org/ns/shacl#>

template idstt:property-annotation(?class, ?property) {

    if (bound(?maxCount) && ?maxCount = 1, "@NotNull",
    if (!bound(?maxCount) || (?maxCount - ?minCount) > 1, "@NotEmpty",
      "!!unknownConstraint!!"))

}
where {
    ?class rdfs:subClassOf* ?superClass .
    ?shape sh:targetClass ?superClass ;
        sh:property ?propShape .
    ?propShape sh:path ?property ;
        sh:minCount ?minCount .
    OPTIONAL {
        ?propShape sh:maxCount ?maxCount .
    }
    FILTER (bound(?minCount) && ?minCount > 0) .
} LIMIT 1
