prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:to_bean_name(?class) {
    concat(
        replace(str(?class), "^.*[/#]([^/#]+)/?", "$1"),
        "Impl"
    )
}
where {}
