prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:to_builder_name(?class) {
    concat(
        replace(str(?class), "^.*[/#]([^/#]+)/?", "$1"),
        "Builder"
    )
}
where {}
