prefix ids: <https://w3id.org/idsa/core/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:all_classes {

    "{\n  \"@context\" : {\n"

#    st:call-template(ids:process-classes)
#    st:call-template(ids:process-properties)

    "\n  }\n}"
}
where {
}

