prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template idstt:classes-properties-instances {

    "{\n  \"@context\" : {\n"

    "  \"ids\" : \"https://w3id.org/idsa/core/\"\n"
    "  ,\"idsc\" : \"https://w3id.org/idsa/code/\"\n"

    st:call-template(idstt:process-class-to-context)
    st:call-template(idstt:process-property-to-context)
    st:call-template(idstt:process-instance-to-context)

    "\n  }\n}"
}
where {
}

