prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template idstt:process-property-to-context {
    # backwards compatibility: if pluralLabel exists, also create an entry with it and the singular URI
    # plural URIs have been used but are not w.r.t. the InformationModel
    if(st:call-template(idstt:to_property_name, ?property) != st:call-template(idstt:to_class_name, ?property),
    concat("  ,\"", st:call-template(idstt:to_property_name, ?property), "\" : ",
    "\"ids:", st:call-template(idstt:to_class_name, ?property), "\"\n"), "")

    # always create the singular URI (no used by the InformationModel Java library)
    "  ,\"" st:call-template(idstt:to_class_name, ?property) "\" : "
        "\"ids:" st:call-template(idstt:to_class_name, ?property) "\""

}
where {
    {?property a owl:DatatypeProperty}

    union

    {?property a owl:ObjectProperty}
}

