prefix ids: <https://w3id.org/idsa/core/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template ids:process-property-to-context {

    "  ,\"" st:call-template(idstt:to_property_name, ?property) "\" : "
    "\"ids:" st:call-template(idstt:to_property_name, ?property) "\""

}
where {
    {?property a owl:DatatypeProperty}

    union

    {?property a owl:ObjectProperty}
}

