prefix ids: <https://w3id.org/idsa/core/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template ids:process-class-to-context {

    "  \"" st:call-template(idstt:to_class_name, ?class) "\" : "
    "\"ids:" st:call-template(idstt:to_class_name, ?class) "\","

}
where {
    ?class a owl:Class.
}

