prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template idstt:process-class-to-context {

    "  ,\"" st:call-template(idstt:to_class_name, ?class) "\" : "
    "\"ids:" st:call-template(idstt:to_class_name, ?class) "\""

}
where {
    ?class a owl:Class.
    FILTER(REGEX(STR(?class), "[a-zA-Z]{2,}")) . # filter out the blank nodes
}

