prefix idstt: <https://w3id.org/idsa/transformationtemplates/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Surround the actual content with plantuml meta information and start the three main information generation processes.

template idstt:all_classes {

    "@startuml\n\n"
    "skinparam linetype ortho\n"
    "title " st:get-title() " - Class Diagram\n"

    st:call-template(idstt:process-class-to-uml)
    st:call-template(idstt:property-relations-to-uml)
    st:call-template(idstt:subclass-relations-to-uml)

    "@enduml\n"

}
where {
}

