prefix ids: <https://w3id.org/idsa/core/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix idstt: <https://w3id.org/idsa/transformationtemplates/>

template ids:property-relations-to-uml {

    "\n"

    st:call-template(idstt:to_class_name, ?domain)

    " --> "

    st:call-template(ids:uml-headlabel, ?domain, ?property)
    st:call-template(idstt:to_class_name, ?range)

    ": "

    str(?propLabel) "\n"

}
where {
    ?property rdfs:domain ?domain;
        rdfs:range ?range;
        rdfs:label ?propLabel.

    FILTER (strstarts(str(?domain), str(<ids:>)) && strstarts(str(?range), str(<ids:>)))
}

