prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>

template ids:property-to-getter-method(?property, ?class) {

    "\n\t"

    st:call-template(ids:propertyAnnotation, ?class, ?property, ?range)

    "\n\t"

    st:call-template(ids:range-to-java-type, ?class, ?property, ?range, "<", ">")

    " "

    # method name
    "get" ucase(substr(str(?label), 1, 1)) substr(str(?label), 2) "()"

}
where  {
   ?property rdfs:label ?label;
        rdfs:range ?range.
}
