prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix valid: <http://industrialdataspace.org/2017/01/ids/validation#>
prefix idoc: <http://industrialdataspace.org/2017/01/ids/documentation#>

template ids:property-to-field(?property, ?class) {

    "\n\t"

    st:call-template(ids:propertyAnnotation, ?class, ?property, ?range)

    " "

    st:call-template(ids:range-to-java-type, ?class, ?property, ?range, "<", ">")

    " "
    if (bound(?pluralLabel), str(?pluralLabel), str(?label))
    ";"
}
where  {
   ?property rdfs:range ?range.

   ?property rdfs:label ?label.
   OPTIONAL {?property idoc:labelPluralForm ?pluralLabel}
}
