prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>

template ids:properties-to-interface-methods(?class) {

	# Iterates on selected properties and writes getter and setter methods

    # getter method signature

    if (bound(?comment),
        concat("\n\t/* ", str(?comment), " */"),
        "")

    "\n\t@RdfProperty(\"" str(?property) "\")"

	st:call-template(ids:property-to-getter-method, ?property, ?class) ";"

}
where  {   
  ?property rdfs:domain ?class;
    rdfs:label ?label.

  OPTIONAL {
    ?property rdfs:comment ?comment.
  }
}
