prefix idsv: <http://industrialdataspace.org/2016/10/idsv/core#>
prefix dcat: <http://www.w3.org/ns/dcat#>

template{

	kg:write(concat("/tmp/",strafter(str(?classWithNoInstances), "#"), "Impl.java"),
		st:call-template(idsv:process-class-to-class, ?classWithNoInstances))

    kg:write(concat("/tmp/",strafter(str(?classWithInstances), "#"), ".java"),
        st:call-template(idsv:process-class-to-enum, ?classWithInstances))

    kg:write(concat("/tmp/",strafter(str(?classWithNoInstances), "#"), ".java"),
        st:call-template(idsv:process-class-to-interface, ?classWithNoInstances))

}
where  {
    ?classWithNoInstances a owl:Class.
    ?classWithInstances a owl:Class.

    FILTER EXISTS {?instance a ?classWithInstances}
    FILTER NOT EXISTS {?instance a ?classWithNoInstances}
}
