prefix idsv: <http://industrialdataspace.org/2016/10/idsv/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template idsv:process-class-to-interface(?class, ?comment) {

    "package de.fraunhofer.iais.eis;\n"
    "/* " str(?comment) " */\n"
    "public interface " strafter(str(?class), "#")

    if (bound(?superClass) && strstarts(str(?superClass), "http://industrialdataspace.org/"),
        concat(" extends ", strafter(st:call-template(idsv:process-subclass, ?class), ", ")),
        "")

    " {\n"

        "\n\t// standard methods\n"

        "\n\t@javax.validation.constraints.NotNull java.net.URL getId();"
        "\n\tvoid setId(@javax.validation.constraints.NotNull java.net.URL url);"
        "\n"
        "\n\tvoid setReadOnly();\n"

        "\n\t// accessor methods as derived from vocabulary"
        "\n"
        st:call-template(idsv:process-properties, ?class)

    "\n}\n"

}
where{
    ?class a owl:Class.
    OPTIONAL {
        ?class rdfs:subClassOf ?superClass.
    }
    FILTER NOT EXISTS {?instance a ?class}
}
GROUP BY ?class
