prefix idsv: <http://industrialdataspace.org/2016/10/idsv/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template idsv:process-class-to-class(?class) {

    "package de.fraunhofer.iais.eis;\n\n"
    "import de.fraunhofer.iais.eis.util.VocabUtil;\n\n"
    "/* " str(?comment) " */\n"
    "public class " concat(strafter(str(?class), "#"), "Impl")
    " implements de.fraunhofer.iais.eis." strafter(str(?class), "#")

    " {\n"

    # boilerplate methods

    "\n\tprivate java.net.URL url;"
    "\n\tprivate boolean readOnly;"
    "\n"

    "\n\t// instance fields as derived from vocabulary\n"
    st:call-template(idsv:properties-to-fields, ?class)

    "\n"
    "\n\t// no manual construction"
    "\n\t" strafter(str(?class), "#") "Impl() {"
    "\n\t\turl = VocabUtil.createRandomUrl(\"" lcase(strafter(str(?class), "#")) "\");"
    "\n\t}"
    "\n"
    "\n\t@Override"
    "\n\tfinal public java.net.URL getId() {"
    "\n\t\treturn url;"
    "\n\t}"
    "\n"
    "\n\t@Override"
    "\n\tfinal public void setId(@javax.validation.constraints.NotNull java.net.URL url) {"
    "\n\t\tassertModifiable();"
    "\n\t\tthis.url = url;"
    "\n\t}"
    "\n"
    "\n\tfinal public void setReadOnly() {"
    "\n\t\treadOnly = true;"
    "\n\t}"
    "\n"
    "\n\tprivate void assertModifiable() {"
    "\n\t\tif (readOnly) {"
    "\n\t\t\tthrow new RuntimeException(\"object has been built and cannot be modified anymore\");"
    "\n\t\t}"
    "\n\t}"
    "\n"

    # method implementation

    "\n\t// accessor method implementations as derived from vocabulary"
    "\n"
    st:call-template(idsv:properties-to-methods, ?class, 'class')

    # parent interface methods implementation
    st:call-template(idsv:subclass-to-method, ?class)

    "\n}\n"

}
where{
    ?class a owl:Class;
        rdfs:comment ?comment.

    FILTER NOT EXISTS {?instance a ?class}
}
