prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>

template ids:process-individuals(?class) {

    "\n\t" str(?label) ","

}
where  {
    ?individual a ?class;
        rdfs:label ?label.
}
