prefix idsv: <http://industrialdataspace.org/2016/10/idsv/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template idsv:process-subclass(?class) {

    ", de.fraunhofer.iais.eis." strafter(str(?superClass), "#")

}
where {
    ?class rdfs:subClassOf ?superClass.
}
