prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:process-class-to-builder(?class) {

    "package de.fraunhofer.iais.eis;\n\n"
    "import de.fraunhofer.iais.eis.util.VocabUtil;\n\n"
    "public class " concat(strafter(str(?class), "#"), "Builder")

    " {\n"

    "\n\tprivate " strafter(str(?class), '#') "Impl " lcase(substr(str(?label), 1, 1)) substr(str(?label), 2) ";"

    # constructor

    "\n"
    "\n\tpublic " strafter(str(?class), "#") "Builder() {"
    "\n\t\t"
        lcase(substr(str(?label), 1, 1)) substr(str(?label), 2) " = new " strafter(str(?class), "#") "Impl();"
        "\n\t\t"
        lcase(substr(str(?label), 1, 1)) substr(str(?label), 2)
        ".url = VocabUtil.createRandomUrl(\""
        lcase(substr(str(?label), 1, 1)) substr(str(?label), 2)
        "\");"
    "\n\t}"
    "\n"
    "\n\tpublic " strafter(str(?class), "#") "Builder(@javax.validation.constraints.NotNull java.net.URL url) {"
    "\n\t\t"
    "this();"
    "\n\t\t"
    lcase(substr(str(?label), 1, 1)) substr(str(?label), 2) ".url = url;"
    "\n\t}"
    "\n"

    # method implementation

    st:call-template(ids:subclass-properties-to-methods, ?class, 'builder')

    # build method

     "\n\tpublic final " strafter(str(?class), "#") " build() throws de.fraunhofer.iais.eis.util.ConstraintViolationException {"
     "\n\t\tcreationHook("
     lcase(substr(str(?label), 1, 1)) substr(str(?label), 2)
     ");"
     "\n\t\tVocabUtil.validate(" lcase(substr(str(?label), 1, 1)) substr(str(?label), 2) ");"
     "\n\t\treturn " lcase(substr(str(?label), 1, 1)) substr(str(?label), 2) ";"
     "\n\t}"

    # creation hook
    "\n"
    "\n\tpublic void creationHook("
    strafter(str(?class), '#')" " lcase(substr(str(?label), 1, 1)) substr(str(?label), 2)
    ") throws de.fraunhofer.iais.eis.util.ConstraintViolationException {"
    "\n\t\t// override me!"
    "\n\t}"

    "\n}\n"

}
where{
    ?class rdfs:label ?label.
}
