prefix idsv: <http://industrialdataspace.org/2016/10/idsv/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template idsv:process-class-to-class(?class, ?comment) {

    "package de.fraunhofer.iais.eis;\n\n"
    "/* " str(?comment) " */\n"
    "public class " concat(strafter(str(?class), "#"), "Impl")
    " implements de.fraunhofer.iais.eis." strafter(str(?class), "#")

    " {\n"

    # boilerplate methods

    "\n\tprivate java.net.URL url;"
    "\n\tprivate boolean readOnly;"

    "\n\t// no manual construction"
    "\n\tDatasetImpl() {
        "\n\t\turl = VocabUtil.createRandomUrl("dataset");
    "\n\t}

    "\n\t@Override
    "\n\tfinal public java.net.URL getId() {
    "\n\t\treturn url;
    "\n\t}

"\n\t        @Override
"\n\t        final public void setId(@NotNull java.net.URL url) {
"\n\t\t            assertModifiable();
"\n\t\t            this.url = url;
"\n\t        }

"\n\t        final public void setReadOnly() {
"\n\t\t            readOnly = true;
"\n\t        }

"\n\t        private void assertModifiable() {
"\n\t\t            if (readOnly) {
"\n\t\t\ŧ                throw new RuntimeException("object has been built and cannot be modified anymore");
"\n\t\t            }
"\n\t        }

    # method implementation

    "\n\t// accessor method implementations as derived from vocabulary"
    "\n"
    # st:call-template(idsv:process-properties, ?class)

    "\n}\n"

}
where{
    ?class a owl:Class.
    FILTER NOT EXISTS {?instance a ?class}
}
