prefix idsv: <http://industrialdataspace.org/2016/10/idsv/core#>
prefix valid: <http://industrialdataspace.org/2017/01/idsv/validation#>

template idsv:property-to-field(?property, ?class) {

    "\n\t"
    "private "
    st:call-template(idsv:range, ?range)
    " "
    strafter(str(?property), "#")
    ";"

}
where  {
   ?property rdfs:label ?label;
        rdfs:range ?range.

} 
