prefix idsv: <http://industrialdataspace.org/2016/10/idsv/core#>
prefix valid: <http://industrialdataspace.org/2017/01/idsv/validation#>

template idsv:property-to-field(?property, ?class) {

    "\n\t"
    "private "

    if (bound(?constraint),
        st:call-template(idsv:propertyAnnotation, ?constraint, ?range),
        st:call-template(idsv:range, ?range))

    " "
    strafter(str(?property), "#")
    ";"

}
where  {
   ?property rdfs:label ?label;
        rdfs:range ?range.

    OPTIONAL {
        ?class idsv:validation ?validation.
        ?validation owl:onProperty ?property.
        ?validation valid:constraint ?constraint.
    }
} 
