prefix idsv: <http://industrialdataspace.org/2016/10/idsv/core#> 

template idsv:properties-to-builder-methods(?rootClass, ?class) {

	# Iterates on selected properties and writes getter and setter methods

	"\n\t"

    # visibility modifier
    "final public "

    # return type and name
    strafter(str(?rootClass), '#') "Builder " str(?label)

	st:call-template(idsv:property-to-setter-method, ?property, ?class)

    # method body
	st:call-template(idsv:setter-method-builder-body, ?property, ?rootClass)

    "\n\t"
}
where  {   
  ?property rdfs:domain ?class;
    rdfs:label ?label.
}
