prefix idsv: <http://industrialdataspace.org/2016/10/idsv/core#>

template idsv:property(?property, ?class) {

    # getter method
    #todo: return type xsd->java

    "\n\t" st:call-template(idsv:propertyValidation, ?property, ?class) " "
    str(?range) " " concat("get", ucase(substr(str(?label), 1, 1)), substr(str(?label), 2), "();")

    # setter method
    #todo: parameter type xsd->java

    "\n\tvoid set"
    ucase(substr(str(?label), 1, 1)) substr(str(?label), 2)
    "("
        st:call-template(idsv:propertyValidation, ?property, ?class) " "
        str(?range) " " str(?label)
    ");"

    # todo: should support
    # @NotNull XMLGregorianCalendar getCreationDate();
    # void setCreationDate(@NotNull XMLGregorianCalendar creationDate);

}
where  {
   ?property rdfs:range ?range;
       rdfs:label ?label.

} 
