prefix idsv: <http://industrialdataspace.org/2016/10/idsv/core#> 

template idsv:properties-to-interface-methods(?class) {

	# Iterates on selected properties and writes getter and setter methods

    # getter method signature
	"\n\t" st:call-template(idsv:property-to-getter-method, ?property, ?class) ";"

}
where  {   
  ?property rdfs:domain ?class;
    rdfs:label ?label.
}
