prefix idsv: <http://industrialdataspace.org/2016/10/idsv/core#>
prefix valid: <http://industrialdataspace.org/2017/01/idsv/validation#>

template idsv:property-to-setter-method(?property, ?class, ?syntax) {

    # visibility modifier
    if (str(?syntax) = 'bean', 'final public ', '')

    # method name
    "void set" ucase(substr(str(?label), 1, 1)) substr(str(?label), 2)

    # method params
    "("
        # parameter type and annotation
        if (bound(?constraint),
            st:call-template(idsv:propertyAnnotation, ?constraint, ?range),
            st:call-template(idsv:range, ?range))

        " "

        # parameter label
        str(?label)
    ")"

    if (str(?syntax) = 'bean', st:call-template(idsv:setter-method-body, ?property), ';')

}
where  {
   ?property rdfs:label ?label;
        rdfs:range ?range.

    OPTIONAL {
        ?class idsv:validation ?validation.
        ?validation owl:onProperty ?property.
        ?validation valid:constraint ?constraint.
    }

} 
