prefix idsv: <http://industrialdataspace.org/2016/10/idsv/core#>

template idsv:propertyAnnotation(?constraint, ?range) {

    if (str(?constraint) = "@OneToMany", "java.util.Collection<", concat(str(?constraint), " "))

    # return type
    st:call-template(idsv:range, ?range)

    if (str(?constraint) = "@OneToMany", ">", "")
}
where {
}
