prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix valid: <http://industrialdataspace.org/2017/01/ids/validation#>

template ids:property-to-getter-method(?property, ?class) {

    # return type and annotation
    if (bound(?constraint),
        st:call-template(ids:propertyAnnotation, ?constraint, ?range),
        st:call-template(ids:range, ?range))

    " "

    # method name
    "get" ucase(substr(str(?label), 1, 1)) substr(str(?label), 2) "()"

}
where  {
   ?property rdfs:label ?label;
        rdfs:range ?range.

    OPTIONAL {
        ?class ids:validation ?validation.
        ?validation owl:onProperty ?property.
        ?validation valid:constraint ?constraint.
    }

} 
