prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix valid: <http://industrialdataspace.org/2017/01/idsv/validation#>

template ids:property-to-setter-method(?property, ?class) {

    # method params
    "("
        # parameter type and annotation
        if (bound(?constraint),
            st:call-template(ids:propertyAnnotation, ?constraint, ?range),
            st:call-template(ids:range, ?range))

        " "

        # parameter label
        strafter(str(?property), "#")
    ")"

}
where  {
   ?property rdfs:range ?range.

    OPTIONAL {
        ?class ids:validation ?validation.
        ?validation owl:onProperty ?property.
        ?validation valid:constraint ?constraint.
    }

} 
