prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

template ids:range(?range) {

    if (str(?range) = str(<xsd:dateTime>), "javax.xml.datatype.XMLGregorianCalendar",
    if (str(?range) = str(<xsd:string>), "java.lang.String",
    if (str(?range) = str(<xsd:integer>), "java.math.BigInteger",
    if (str(?range) = str(<xsd:int>), "int",
    if (str(?range) = str(<xsd:long>), "long",
    if (str(?range) = str(<xsd:short>), "short",
    if (str(?range) = str(<xsd:float>), "float",
    if (str(?range) = str(<xsd:double>), "double",
    if (str(?range) = str(<xsd:boolean>), "boolean",
    if (str(?range) = str(<xsd:byte>), "byte",
    if (str(?range) = str(<xsd:base64Binary>), "byte[]",
    if (str(?range) = str(<xsd:time>), "javax.xml.datatype.XMLGregorianCalendar",
    if (str(?range) = str(<xsd:date>), "javax.xml.datatype.XMLGregorianCalendar",
    if (str(?range) = str(<xsd:anyURI>), "java.net.URL",
    if (str(?range) = str(<rdfs:Literal>), "org.apache.jena.rdf.model.Literal",

    if (strstarts(str(?range), "http://industrialdataspace.org/"), concat("de.fraunhofer.iais.eis.", strafter(?range, "#")),
    "!!unknownType!!"))))))))))))))))

}
where {
}
