prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:setter-method-builder-body(?property, ?class) {

    " {"

    "\n\t\t"
    lcase(substr(str(?classLabel), 1, 1)) substr(str(?classLabel), 2)
    "." strafter(str(?property), "#") " = " strafter(str(?property), "#") ";"

    "\n\t\treturn this;"

    "\n\t}"

}
where{
    ?class rdfs:label ?classLabel.
}
