prefix idsv: <http://industrialdataspace.org/2016/10/idsv/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template idsv:subclass-properties-to-fields(?class) {

    st:call-template(idsv:properties-to-fields, ?superClass, 'bean')

}
where {
    ?class a owl:Class;
        rdfs:subClassOf* ?superClass.

}
