prefix ids: <https://schema.industrialdataspace.org/>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix trns: <https://schema.iais.fraunhofer.de/ids/helper/transformation/>

template ids:class-tbox(?class) {

    if (!bound(?isAbstract) || (?isAbstract = false),
        kg:write(concat("/tmp/",str(?label), "Impl.java"),
            st:call-template(ids:process-class-to-bean, ?class)),
        '')

    kg:write(concat("/tmp/", str(?label), ".java"),
        st:call-template(ids:process-class-to-interface, ?class))

}
where  {
    ?class a owl:Class.
    ?class rdfs:label ?label .

    filter (lang(?label) = "en")
    optional {?class trns:isAbstract ?isAbstract}
}

