prefix ids: <https://schema.industrialdataspace.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix idoc: <https://schema.iais.fraunhofer.de/ids/helper/documentation/>

template ids:setter-method-body(?property) {

    " {"

    "\n\t\t"
    "this."
    if (bound(?pluralLabel), str(?pluralLabel), str(?label))
    " = "
    if (bound(?pluralLabel), str(?pluralLabel), str(?label))
    ";"
    "\n\t}"

}
where{
    ?property rdfs:label ?label.
    OPTIONAL {?property idoc:labelPluralForm ?pluralLabel}
}
