prefix ids: <https://schema.industrialdataspace.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix idoc: <https://schema.iais.fraunhofer.de/ids/helper/documentation/>

template ids:setter-method-body(?property, ?class) {

    " {"

    "\n\t\t"
    lcase(substr(str(?classLabel), 1, 1)) substr(str(?classLabel), 2)
    "."
    if (bound(?pluralLabel), str(?pluralLabel), str(?label))
    " = "
    if (bound(?pluralLabel), str(?pluralLabel), str(?label))
    ";"
    "\n\t\treturn this;"

    "\n\t}"

}
where{
    ?class rdfs:label ?classLabel.

    ?property rdfs:label ?label.
    OPTIONAL {?property idoc:labelPluralForm ?pluralLabel}
}
