prefix ids: <https://w3id.org/ids/core/>
prefix dcat: <http://www.w3.org/ns/dcat#>

template st:start {

    if (bound(?instance),
        st:call-template(ids:class-abox, ?class),
        st:call-template(ids:class-tbox, ?class))

}
where  {
    ?class a owl:Class.
    OPTIONAL {
        ?instance a ?class
    }
}
group by ?class
