prefix ids: <http://industrialdataspace.org/2016/10/ids/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

template ids:getter-method-body(?property) {

    " {"
    "\n\t\treturn " strafter(str(?property), "#") ";"
    "\n\t}"

}
where{
}
